apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    app: sftp-deployment
  name: sftp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        app: sftp
    spec:
      containers:
        - command: ["./entrypoint"]
          args: ["foo:pass:::upload"]
          image: atmoz/sftp
          name: sftp
          ports:
            - containerPort: 22
          resources: {}
          volumeMounts:
            - mountPath: /home/foo/upload
              name: sftp-claim
      restartPolicy: Always
      volumes:
        - name: sftp-claim
          persistentVolumeClaim:
            claimName: local-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: sftp-service
  name: sftp-service
spec:
  type: NodePort
  ports:
    - name: "30220"
      port: 22      
      nodePort: 30220
  selector:
    app: sftp
status:
  loadBalancer: {}
