version: '3'

services:
  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80" #tell traefik to listen for connections on port 80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false 
      - traefik.http.routers.traefik_https.rule=Host(`host.docker.internal`)

  showcase:    
    image: tui-web:4.0
    container_name: tui-web
    ports:
      - 8081:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    labels:
     - traefik.enable=true
     - traefik.http.routers.showcase.rule=Host(`localhost`) && (PathPrefix(`//whoami/`) || PathPrefix(`/portainer`))
     - traefik.http.routers.showcase.entrypoints=web 
     - traefik.http.services.showcase.loadbalancer.server.port=8081   
     #- traefik.http.middlewares.showcase.stripprefix.prefixes=/web1
     - "traefik.http.middlewares.showcase.stripprefix.prefixes=/whoami" 
     - "traefik.http.middlewares.showcase.stripprefix.forceslash=true"   
     - "traefik.http.routers.app.middlewares=showcase"      
    restart: unless-stopped

  whoami2:
    image: "nginxdemos/hello"
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`localhost`) && Path(`/whoami2`)"
      - "traefik.http.routers.whoami2.entrypoints=web"